type = "awards"
title = "Awards"
description = "Selected honors and awards."

[[items]]
title = "National Scholarship"
date = "2025"

[[items]]
title = "National Scholarship"
date = "2024"

[[items]]
title = "ICPC World Finals Qualifier (World Finalist)"
date = "2026"

[[items]]
title = "ICPC Regional Contest Gold Medal (10th Place in Shanghai Division)"
date = "2025"

[[items]]
title = "ICPC Regional Contest Gold Medal (Shenyang Division)"
date = "2025"

[[items]]
title = "CCPC Regional Contest Gold Medal (Chongqing Division)"
date = "2025"

[[items]]
title = "International Robot Simulation Competition Gold Medal (2nd Place)"
date = "2025"

[[items]]
title = "International Robot Simulation Competition Gold Medal (2nd Place)"
date = "2024"

[[items]]
title = "Huawei Ascend AI Innovation Competition National Finals Gold Medal (2nd Place)"
date = "2025"

[[items]]
title = "ICPC Invitational Contest Gold Medal (4th Place in Xi'an Division)"
date = "2025"

[[items]]
title = "Shaanxi Provincial College Programming Competition Champion"
date = "2025"

[[items]]
title = "Shaanxi Provincial College Programming Competition Champion"
date = "2024"

[[items]]
title = "National Olympiad in Informatics in Provinces First Prize"
date = "2021"
