type = "card"
title = "Awards"
description = "Selected Honors and awards I have received.My Full Awards list could be found in my headpage"

[[items]]
title = "National Scholarship"
subtitle = "National Scholarship for Undergraduate Students"
date = "2024, 2025"
tags = ["National Level", "Most Prestigious", "Scholarship"]

[[items]]
title = "ICPC World Finalist"
subtitle = "50th ICPC World Finals, Hangzhou"
date = "2026.02"
tags = ["ICPC World Final", "International", "Finalist"]

[[items]]
title = "ICPC Shanghai - Gold Medal"
subtitle = "ICPC Asia Regional Contest, 10th Place Overall"
date = "2025.12"
tags = ["Gold Medal", "Regional Finalist", "Top 10"]

[[items]]
title = "ICPC Shenyang - Gold Medal"
subtitle = "ICPC Asia Regional Contest"
date = "2025.12"
tags = ["Gold Medal", "Regional"]

[[items]]
title = "CCPC Chongqing - Gold Medal"
subtitle = "China Collegiate Programming Contest"
date = "2025.12"
tags = ["Gold Medal", "CCPC"]

[[items]]
title = "Codeforces Grandmaster"
subtitle = "Codeforces Rating System, Highest Rating Level"
date = "2025.12"
tags = ["Grandmaster", "Codeforces", "Top Rating"]

[[items]]
title = "NOIP First Prize"
subtitle = "National Olympiad in Informatics in Provinces"
date = "2021"
tags = ["National Level", "High School", "NOIP"]

[[items]]
title = "Robotics Contest - Gold Medal"
subtitle = "International Advanced Robotics and Simulation Competition"
date = "2024, 2025"
tags = ["Gold Medal", "International", "Robotics"]

[[items]]
title = "Shaanxi Programming Champion"
subtitle = "Shaanxi Provincial College Programming Contest"
date = "2024, 2025"
tags = ["Champion", "Provincial", "1st Place"]

[[items]]
title = "ACM MM 2025 Oral"
subtitle = "ACM Multimedia 2025 - Oral Presentation"
date = "2025.07"
tags = ["Oral Presentation", "ACM MM", "Top-tier Conference"]
