
[[news]]
date = "2026.05"
content = "I get the sense time scholar,which scores the top 30 undergraduates in the area of ai in china."


[[news]]
date = "2026.05"
content = "I get the sense time scholar,which scores the top 30 undergraduates in the area of ai in china."


[[news]]
date = "2026.05"
content = "Our work CodeHacker is selected as one oral work in ACL'26."

[[news]]
date = "2026.04"
content = "Our work LatentMorph is accepted at the ICML'26."

[[news]]
date = "2026.04"
content = "Our work CodeHacker is accepted at the ACL'26."

[[news]]
date = "2026.03"
content = "Our work LatentMorph has been reported by public media."

[[news]]
date = "2026.01"
content = "Qualified for the 50th ICPC World Finals in Hangzhou. Submitted two papers to ACL'26 and ICML'26"

[[news]]
date = "2025.12"
content = "Achieved Codeforces Grandmaster rank."

[[news]]
date = "2025.12"
content = "Won gold medals at ICPC Shenyang, ICPC Shanghai (10th place), and CCPC Chongqing."

[[news]]
date = "2025.11"
content = "Won 2nd place at International Advanced Robot & Simulation Technology Competition in Qingdao."

[[news]]
date = "2025.07"
content = "Our paper FineQuest was accepted at the ACM International Conference on Multimedia 2025 as an oral presentation."

[[news]]
date = "2025.05"
content = "Won Shaanxi Provincial Programming Contest Championship."
