type = "services"
title = "Services"
description = "Professional services and community involvement."

[[items]]
date = "2025 - 2026"
content = "Reviewer for ACL'26 , MIR."

[[items]]
date = "2024 - 2026"
content = "Team leader of the Northwestern Polytechnical University ICPC team."
